name: Dev Thoughts
title: Brad McDavid
email: brad.mcdavid@gmail.com
description: A place to share stuff (do better)
url: "https://bmcdavid.github.io"
twitter_username: bsm44
github_username:  bmcdavid
markdown: kramdown
paginate: 1
#permalink: /:title/
paginate_path: blog/page:num/
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - temp/
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - package-lock.json