name: Dev Thoughts
title: Brad McDavid
email: brad.mcdavid@gmail.com
description: A place to share stuff (do better)
url: "https://bmcdavid.github.io"
twitter_username: bsm44
github_username:  bmcdavid
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - temp/
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - package-lock.json